# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jm81-whois}
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jared Morgan"]
  s.date = %q{2010-08-29}
  s.description = %q{This library presents whois information for domains in a variety of TLD's 
through a standardized API.
}
  s.email = %q{jmorgan@morgancreative.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "jm81-whois.gemspec",
     "lib/whois.rb",
     "lib/whois/domain.rb",
     "lib/whois/domain/aero.rb",
     "lib/whois/domain/afilias.rb",
     "lib/whois/domain/base.rb",
     "lib/whois/domain/cat.rb",
     "lib/whois/domain/coop.rb",
     "lib/whois/domain/cz.rb",
     "lib/whois/domain/educause.rb",
     "lib/whois/domain/gov.rb",
     "lib/whois/domain/int.rb",
     "lib/whois/domain/mobi.rb",
     "lib/whois/domain/museum.rb",
     "lib/whois/domain/name.rb",
     "lib/whois/domain/neustar.rb",
     "lib/whois/domain/pro.rb",
     "lib/whois/domain/public_interest.rb",
     "lib/whois/domain/ru.rb",
     "lib/whois/domain/su.rb",
     "lib/whois/domain/verisign_grs.rb",
     "lib/whois/domain/ws.rb",
     "lib/whois/version.rb",
     "test/test_helper.rb",
     "test/whois/domain/aero_test.rb",
     "test/whois/domain/afilias_test.rb",
     "test/whois/domain/cat_test.rb",
     "test/whois/domain/coop_test.rb",
     "test/whois/domain/educause_test.rb",
     "test/whois/domain/gov_test.rb",
     "test/whois/domain/int_test.rb",
     "test/whois/domain/mobi_test.rb",
     "test/whois/domain/museum_test.rb",
     "test/whois/domain/name_test.rb",
     "test/whois/domain/neustar_test.rb",
     "test/whois/domain/pro_test.rb",
     "test/whois/domain/public_interest_test.rb",
     "test/whois/domain/verisign_grs_test.rb",
     "test/whois/domain/ws_test.rb",
     "test/whois/domain_test.rb"
  ]
  s.homepage = %q{http://github.com/jm81/whois}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby library for accessing Whois information}
  s.test_files = [
    "test/test_helper.rb",
     "test/whois/domain_test.rb",
     "test/whois/domain/ws_test.rb",
     "test/whois/domain/educause_test.rb",
     "test/whois/domain/neustar_test.rb",
     "test/whois/domain/cat_test.rb",
     "test/whois/domain/name_test.rb",
     "test/whois/domain/museum_test.rb",
     "test/whois/domain/verisign_grs_test.rb",
     "test/whois/domain/public_interest_test.rb",
     "test/whois/domain/pro_test.rb",
     "test/whois/domain/mobi_test.rb",
     "test/whois/domain/coop_test.rb",
     "test/whois/domain/aero_test.rb",
     "test/whois/domain/gov_test.rb",
     "test/whois/domain/int_test.rb",
     "test/whois/domain/afilias_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

